### ISSUE TITLE
用linux登录第一步就出现问题了，怎么解决啊

### ISSUE THREAD

**Issue by Rixo1043** [atupal/cliqq#13]
读取cookie失败 [Errno 2] No such file or directory: 'res/loginGet.cookie'
Traceback (most recent call last):
  File "runqq.py", line 111, in <module>
    Q.run()
  File "runqq.py", line 92, in run
    self.qq.getSafeCode()
  File "/root/桌面/cliqq-dev/qq/login_qq.py", line 82, in getSafeCode
    self.check = verifycode.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

这个是问题描述，看了login_qq.py里面的代码，这里的url没看懂，然后返回出来做正则表达式的部分没看懂是啥，就卡住了，就帮忙解决下啊

**Comment by Rixo1043** [comment]
url = (
                'https://ssl.ptlogin2.qq.com/check?uin='  +
                str(self.user) + '&appid=1003903&js_ver=10017&js_type=0'
                '&login_sig=0ihp3t5ghfoonssle-98x9hy4uaqmpvu*8*odgl5vyerelcb8fk-y3ts6c3*7e8-'
                '&u1=http%3A%2F%2Fweb2.qq.com%2Floginproxy.html&r=' + str(random.random())
                )
        req = urllib2.Request(url)
        #self.mycookie += "confirmuin=" + self.user + ";"
        #req.add_header('Cookie', self.mycookie)
        req  = urllib2.urlopen(req)
        #cs = ['%s=%s' %  (c.name, c.value) for c in self.cookies]
        #self.mycookie += ";".join(cs)
verifycode = re.search(r"'(\d)','(.+)','(.+)'", req.read())

就这串代码，需要有什么前置知识吗？

**Comment by atupal** [comment]
只需要一些 http 协议和非常基础的正则表达式知识。

腾讯的 webqq 已关闭，这些街口都用不了了。所以代码也不会工作。
