### ISSUE TITLE
获取组出错 了额

### ISSUE THREAD

**Issue by lanx-x** [atupal/cliqq#2]
读取cookie失败 [Errno 2] No such file or directory: 'res/loginGet.cookie'
0 !AOT \x00\x00\x00\x00\x18\xc2\x5c\xe1
ptuiCB('0','0','http://web2.qq.com/loginproxy.html?login2qq=1&webqq_type=10','0','登录成功！', 'KING');

ETK :
confirmuin : 0
ptuserinfo : 4b494exxx
ptvfsession : fe907cxxx
superkey : gjwngxMNGaM1xxx
supertoken : 12317xx
superuin : o0415xx
RK : ynRxx
pt2gguin : o0415390945
ptcz : 7fb6503904e0b42df4bc1d18d2955b4e24e1acb338fd8xxx
ptisp : ctc
ptwebqq : e8bae081ac1a597e3c0dcdfa1bdff4443e109f5e904ba8xxx
skey : @FoD7Zxxx
uin : o0415390945
{"c":1,"e":""}
103
Traceback (most recent call last):
  File "qq/runqq.py", line 111, in <module>
    Q.run()
  File "qq/runqq.py", line 95, in run
    self.qq.getGroupList()
  File "/home/king/cliqq/qq/login_qq.py", line 204, in getGroupList
    data = 'r=%7B%22vfwebqq%22%3A%22'+self.result['result']['vfwebqq'] +'%22%7D'
KeyError: 'result'

**Comment by atupal** [comment]
由于又改hash算法了所以出错了。dev分支已经修复了，请使用dev分支，由于种种原因一直没有合并到master分支上。。。。
